### ISSUE TITLE
0.1.6 crash at Nisan Mausoleum

### ISSUE THREAD

**Issue by jianpan** [NoharOSP/Perfect_Works_Build#185]
There are 2 doors on the second floor of mausoleum. The one to the elevator works, but DuckStation on Android crashes when opening the other door to the control room. I have a memcard file if you want to reproduce the problem.

**Comment by NoharOSP** [comment]
Sorry for the late response. If you could send the memcard, that would be splendid.

**Comment by jianpan** [comment]
[Xenogears.zip](https://github.com/NoharOSP/Perfect_Works_Build/files/11024033/Xenogears.zip)

The save should be the 3rd one in the first column. It's the save point on the 3rd floor of mausoleum.

**Comment by NoharOSP** [comment]
Before I test this, do you know what patches you applied?

**Comment by jianpan** [comment]
All of them in 0.1.6

**Comment by NoharOSP** [comment]
The problem is due to a conflict between the script patch and the fast text patch as the bridge in the Nisan Mausoleum was edited in the latter of the two. This will be remedied for version 0.1.7; but if you want to keep playing now, make a new ROM where fast text isn't applied, then turn it back on after clearing the dungeon.

**Comment by jianpan** [comment]
Good to know. Thanks.

**Comment by NoharOSP** [comment]
0.1.7 now has a work around to this freeze.
